import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1752381143710 implements MigrationInterface {
    name = 'Migration1752381143710'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "term" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "termKo" character varying(100) NOT NULL, "termEn" character varying(100), "termHanja" character varying(100), "definition" text NOT NULL, "description" text, "visualType" character varying(20), "visualUrl" text, "visualCode" text, "audioUrl" text, "isPublished" boolean NOT NULL DEFAULT true, "categoryId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_55b0479f0743f2e5d5ec414821e" PRIMARY KEY ("id")); COMMENT ON COLUMN "term"."termKo" IS '한글 용어'; COMMENT ON COLUMN "term"."termEn" IS '영어 용어'; COMMENT ON COLUMN "term"."termHanja" IS '한자 용어'; COMMENT ON COLUMN "term"."definition" IS '쉬운 설명(한 줄 요약)'; COMMENT ON COLUMN "term"."description" IS '상세 설명'; COMMENT ON COLUMN "term"."visualType" IS '시각자료 타입(image/mermaid/svg/none)'; COMMENT ON COLUMN "term"."visualUrl" IS '시각자료(이미지/도식) 링크'; COMMENT ON COLUMN "term"."visualCode" IS 'mermaid/SVG 등 그래프 코드'; COMMENT ON COLUMN "term"."audioUrl" IS '발음 듣기(음성 파일 링크)'; COMMENT ON COLUMN "term"."isPublished" IS '공개 여부'; COMMENT ON COLUMN "term"."categoryId" IS '카테고리 ID'; COMMENT ON COLUMN "term"."createdAt" IS '생성일'; COMMENT ON COLUMN "term"."updatedAt" IS '수정일'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "term"`);
    }

}
