import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1752283959253 implements MigrationInterface {
    name = 'Migration1752283959253'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "nickname" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'user', "provider" character varying NOT NULL, "providerId" character varying NOT NULL, "profileImageUrl" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e2364281027b926b879fa2fa1e0" UNIQUE ("nickname"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")); COMMENT ON COLUMN "user"."id" IS '사용자 ID'; COMMENT ON COLUMN "user"."nickname" IS '사용자 닉네임'; COMMENT ON COLUMN "user"."email" IS '사용자 이메일'; COMMENT ON COLUMN "user"."password" IS '사용자 비밀번호'; COMMENT ON COLUMN "user"."role" IS '사용자 역할'; COMMENT ON COLUMN "user"."provider" IS '사용자 프로바이더'; COMMENT ON COLUMN "user"."providerId" IS '사용자 프로바이더 ID'; COMMENT ON COLUMN "user"."profileImageUrl" IS '사용자 프로필 이미지 URL'; COMMENT ON COLUMN "user"."createdAt" IS '사용자 생성일'; COMMENT ON COLUMN "user"."updatedAt" IS '사용자 정보 수정일'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "user"`);
    }

}
