import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1752479479857 implements MigrationInterface {
    name = 'Migration1752479479857'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "term_categories" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(50) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c71999e038f555eedc5605ab8ee" UNIQUE ("name"), CONSTRAINT "PK_a6ad00d19636810ec0c3ad55a23" PRIMARY KEY ("id")); COMMENT ON COLUMN "term_categories"."name" IS '카테고리 이름'; COMMENT ON COLUMN "term_categories"."createdAt" IS '카테고리 생성일'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "term_categories"`);
    }

}
