import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1754809367892 implements MigrationInterface {
    name = 'Migration1754809367892'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "terms" DROP CONSTRAINT "FK_45f6ad23abb6b6afe6bffe041d2"`);
        await queryRunner.query(`CREATE TABLE "quizzes" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "termId" integer, "question" text NOT NULL, "type" character varying(32) NOT NULL, "difficulty" character varying(16) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b24f0f7662cf6b3a0e7dba0a1b4" PRIMARY KEY ("id")); COMMENT ON COLUMN "quizzes"."termId" IS '관련 용어 ID (terms.id)'; COMMENT ON COLUMN "quizzes"."question" IS '문제 내용'; COMMENT ON COLUMN "quizzes"."type" IS '문제 유형(multiple_choice: 객관식 | ox | short_answer: 단답형 | fill_blank: 빈칸 채우기)'; COMMENT ON COLUMN "quizzes"."difficulty" IS '난이도(easy | medium | hard)'; COMMENT ON COLUMN "quizzes"."created_at" IS '생성일시'`);
        await queryRunner.query(`CREATE INDEX "IDX_965429f48bd221d3910220afef" ON "quizzes" ("termId") `);
        await queryRunner.query(`CREATE TABLE "quiz_options" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "quizId" integer NOT NULL, "optionText" text NOT NULL, "isCorrect" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_9c59607f100085ab17f0f138926" PRIMARY KEY ("id")); COMMENT ON COLUMN "quiz_options"."quizId" IS '관련 퀴즈 ID (quizzes.id)'; COMMENT ON COLUMN "quiz_options"."optionText" IS '보기 내용'; COMMENT ON COLUMN "quiz_options"."isCorrect" IS '정답 여부'`);
        await queryRunner.query(`CREATE INDEX "IDX_7f789aa1201a7eea6c8db1851c" ON "quiz_options" ("quizId") `);
        await queryRunner.query(`CREATE TABLE "quiz_results" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "quizId" integer NOT NULL, "userId" character varying(64) NOT NULL, "isCorrect" boolean NOT NULL DEFAULT false, "answered_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4ecf38c5bf5b054ccc9f10e438a" PRIMARY KEY ("id")); COMMENT ON COLUMN "quiz_results"."quizId" IS '퀴즈 ID (quizzes.id)'; COMMENT ON COLUMN "quiz_results"."userId" IS '사용자 ID'; COMMENT ON COLUMN "quiz_results"."isCorrect" IS '정답 여부'; COMMENT ON COLUMN "quiz_results"."answered_at" IS '응답 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_7cda9ec9289f8877d6246a7af6" ON "quiz_results" ("quizId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d2a625978d364b2566b796666" ON "quiz_results" ("userId") `);
        await queryRunner.query(`CREATE TABLE "quiz_tags" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "quizId" integer NOT NULL, "tag" character varying(50) NOT NULL, CONSTRAINT "PK_84f71b788ee0e6cf690119509b0" PRIMARY KEY ("id")); COMMENT ON COLUMN "quiz_tags"."quizId" IS '퀴즈 ID (quizzes.id)'; COMMENT ON COLUMN "quiz_tags"."tag" IS '태그명'`);
        await queryRunner.query(`CREATE INDEX "IDX_038e910cd4adc2ede05a828867" ON "quiz_tags" ("quizId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8bbb6ede9a06f3babc7895901" ON "quiz_tags" ("tag") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_c8bbb6ede9a06f3babc7895901"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_038e910cd4adc2ede05a828867"`);
        await queryRunner.query(`DROP TABLE "quiz_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d2a625978d364b2566b796666"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cda9ec9289f8877d6246a7af6"`);
        await queryRunner.query(`DROP TABLE "quiz_results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f789aa1201a7eea6c8db1851c"`);
        await queryRunner.query(`DROP TABLE "quiz_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_965429f48bd221d3910220afef"`);
        await queryRunner.query(`DROP TABLE "quizzes"`);
        await queryRunner.query(`ALTER TABLE "terms" ADD CONSTRAINT "FK_45f6ad23abb6b6afe6bffe041d2" FOREIGN KEY ("categoryId") REFERENCES "term_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
